name: wajed_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  awesome_notifications: ^0.9.3+1
  flutter_screenutil: ^5.9.1
  # font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.6
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.3+1
  http: ^1.2.1
  fluttertoast: ^8.2.5
  # flutter_secure_storage: ^9.0.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  easy_stepper: ^0.8.3
  flutter_pdfview: ^1.3.2
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  path: any
  image_picker: ^1.1.1
  flutter_rating_bar: ^4.0.1
  get_it: ^7.7.0
  # fl_chart: ^0.63.0
  flutter_share: ^2.0.0
  shimmer: ^3.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  smooth_page_indicator: ^1.1.0
  photo_view: ^0.15.0
  flutter_html: any
  dropdown_button2: ^2.3.9
  getwidget: ^4.0.0
  font_awesome_flutter: ^10.7.0
  moyasar: ^2.0.10




dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/dealer_images/nav_bar/
    - assets/images/dealer_images/
    - assets/images/home/
    - assets/images/svg/
    - assets/images/onboarding/
    - assets/fonts/
    - assets/i18n/
    - assets/icons/


 
  fonts:
    - family: STC
      fonts:
        - asset: assets/fonts/STC-Regular.ttf
        - asset: assets/fonts/STC-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

